Tests for UI in Search
mackenzieleach/screwthereview pull request #76
Opened 2021-05-11 13:23 UTC by rachelye1

2021-05-11 19:12 UTC, luuuk submitted a review, later dismissed

2021-05-12 01:35 UTC, mackenzieleach requested changes
Run "yarn test" locally or use the "checks" tab to see what is failing and resolve them!

2021-05-12 02:27 UTC, rachelye1 commented
Updated test code and addressed feedback

2021-05-12 02:29 UTC, mackenzieleach approved these changes

2021-05-12 02:30 UTC, mackenzieleach approved these changes

2021-05-12 02:31 UTC, merged